Remove tmp dir when failing or finishing

diff --git a/biroamer b/biroamer
--- a/biroamer
+++ b/biroamer
@@ -16,6 +16,7 @@ FASTALIGN=fast_align
 ATOOLS=atools
 export NER=biner
 BUILDTMX=buildtmx
+NODELTEMP=false
 
 JOBS=$(getconf _NPROCESSORS_ONLN)
 BLOCKSIZE=10000
@@ -68,11 +69,12 @@ usage () {
     echo "    -o                Enable random omitting of sentences"
     echo "    -t TOKL1          External tokenizer command for lang1"
     echo "    -T TOKL2          External tokenizer command for lang2"
+    echo "    -p                Do not delete temporary directory"
     echo "    -h                Shows this message"
 }
 
 # Read optional arguments
-while getopts ":s:a:j:b:m:t:T:ho" options
+while getopts ":s:a:j:b:m:t:T:pho" options
 do
     case "${options}" in
         s) SEED=$OPTARG;;
@@ -81,6 +83,7 @@ do
         b) BLOCKSIZE=$OPTARG;;
         m) MIX_CORPUS=$OPTARG;;
         o) OMIT=true;;
+        p) NODELTEMP=true;;
         t) TOKL1=$OPTARG;;
         T) TOKL2=$OPTARG;;
         h) usage
@@ -123,6 +126,10 @@ else
 fi
 
 MYTEMPDIR=$(mktemp -d)
+if [ "$NODELTEMP" = false ]; then
+    # Remove temporary dir when script fails or finishes
+    trap "rm -Rr $MYTEMPDIR" EXIT
+fi
 echo "Using temporary directory $MYTEMPDIR" 1>&2
 
 # Extract from TMX, omit, mix and shuffle
@@ -173,5 +180,3 @@ paste $MYTEMPDIR/omitted-mixed $MYTEMPDIR/f1.tok $MYTEMPDIR/f2.tok $MYTEMPDIR/sy
     | $BUILDTMX $L1 $L2
 
 echo "Removing temporary directory $MYTEMPDIR" 1>&2
-
-rm -Rf $MYTEMPDIR
